### ISSUE TITLE
Newest Commit broke connections

### ISSUE THREAD

**Issue by mbarreca** [gocql/gocql#922]
Hi,

The newest commit has broken the connection to my cassandra cluster.

This line
	
`cluster := gocql.NewCluster("192.168.1.1")`

Outputs this:

`panic: host missing connect ip address`

**Comment by Zariel** [comment]
cc @thrawn01

**Comment by Zariel** [comment]
@mbarreca what version of cassandra and protocol are you using?

**Comment by mbarreca** [comment]
@Zariel it's Cassandra 3.0.9 and the Protocol is v4

**Comment by CodingMinds** [comment]
Same here with Cassandra 3.0.9 and v4

**Comment by mbarreca** [comment]
@Zariel @thrawn01 can you revert to the last commit until further investigation?

**Comment by Zariel** [comment]
I can't reproduce this locally, can you provide more details about the environment?

Is cassandra running in Docker? What are the nodes listen address and rpc_address and broadcast_address?

**Comment by CodingMinds** [comment]
In my case it's an Ubuntu 16.04 VM in Virtual Box.
Single node Cassandra with gocql on same host.

Cassandra configuration:
```yaml
cluster_name: 'Example'
num_tokens: 256
hinted_handoff_enabled: true
max_hint_window_in_ms: 10800000 # 3 hours
hinted_handoff_throttle_in_kb: 1024
max_hints_delivery_threads: 2
hints_flush_period_in_ms: 10000
max_hints_file_size_in_mb: 128
batchlog_replay_throttle_in_kb: 1024
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
role_manager: CassandraRoleManager
roles_validity_in_ms: 2000
permissions_validity_in_ms: 2000
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
data_file_directories:
commitlog_directory: /var/lib/cassandra/commitlog
disk_failure_policy: die
commit_failure_policy: die
key_cache_size_in_mb:
key_cache_save_period: 14400
row_cache_size_in_mb: 0
row_cache_save_period: 0
counter_cache_size_in_mb:
counter_cache_save_period: 7200
saved_caches_directory: /var/lib/cassandra/saved_caches
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 8
concurrent_materialized_view_writes: 32
memtable_allocation_type: offheap_buffers
index_summary_capacity_in_mb:
index_summary_resize_interval_in_minutes: 60
trickle_fsync: true
trickle_fsync_interval_in_kb: 10240
storage_port: 7000
ssl_storage_port: 7001
listen_interface: eth0
listen_on_broadcast_address: true
start_native_transport: true
native_transport_port: 9042
start_rpc: false
rpc_address: 0.0.0.0
rpc_port: 9160
broadcast_rpc_address: 10.0.2.15
rpc_keepalive: true
rpc_server_type: sync
thrift_framed_transport_size_in_mb: 15
incremental_backups: false
snapshot_before_compaction: false
auto_snapshot: true
tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000
column_index_size_in_kb: 64
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
unlogged_batch_across_partitions_warn_threshold: 10
concurrent_compactors: 1
compaction_throughput_mb_per_sec: 250
compaction_large_partition_warning_threshold_mb: 100
sstable_preemptive_open_interval_in_mb: 50
read_request_timeout_in_ms: 5000
range_request_timeout_in_ms: 10000
write_request_timeout_in_ms: 2000
counter_write_request_timeout_in_ms: 5000
cas_contention_timeout_in_ms: 1000
truncate_request_timeout_in_ms: 60000
request_timeout_in_ms: 10000
cross_node_timeout: true
endpoint_snitch: SimpleSnitch
dynamic_snitch_update_interval_in_ms: 100 
dynamic_snitch_reset_interval_in_ms: 600000
dynamic_snitch_badness_threshold: 0.1
request_scheduler: org.apache.cassandra.scheduler.NoScheduler
server_encryption_options:
client_encryption_options:
internode_compression: dc
inter_dc_tcp_nodelay: false
tracetype_query_ttl: 86400
tracetype_repair_ttl: 604800
gc_warn_threshold_in_ms: 500
enable_user_defined_functions: false
enable_scripted_user_defined_functions: false
windows_timer_interval: 1
```

Host IP configuration:
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:45:9a:1b brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:62:68:22 brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.102/24 brd 192.168.56.255 scope global eth1
       valid_lft forever preferred_lft forever
```

Example:
```golang
package main

import (
  "log"
  
  "github.com/gocql/gocql"
)

func main() {
  cluster := gocql.NewCluster("127.0.0.1")
  cluster.Consistency = gocql.One
  session, err := cluster.CreateSession()
  if err != nil {
    log.Fatalf("Cassandra create session error: %s", err)
  }
  _ = session
}
```

Error:
```
GOPATH=${PWD} go build coding-minds.com/xxx/example && ./example
panic: host missing connect ip address

goroutine 1 [running]:
github.com/gocql/gocql.Connect(0xc42007eb00, 0xc420060360, 0x78fe20, 0xc420065080, 0xc42009e000, 0x0, 0x0, 0x0)
	/root/example/src/github.com/gocql/gocql/conn.go:160 +0xf06
github.com/gocql/gocql.(*Session).connect(0xc42009e000, 0xc42007eb00, 0x78fe20, 0xc420065080, 0xc420065080, 0xc420091828, 0x20091828)
	/root/example/src/github.com/gocql/gocql/session.go:636 +0x52
github.com/gocql/gocql.(*hostConnPool).connect(0xc420065080, 0x0, 0x0)
	/root/example/src/github.com/gocql/gocql/connectionpool.go:486 +0x83
github.com/gocql/gocql.(*hostConnPool).fill(0xc420065080)
	/root/example/src/github.com/gocql/gocql/connectionpool.go:396 +0x140
github.com/gocql/gocql.(*policyConnPool).addHost(0xc420060300, 0xc42007eb00)
	/root/example/src/github.com/gocql/gocql/connectionpool.go:219 +0xe5
github.com/gocql/gocql.(*ringDescriber).refreshRing(0xc42001b500, 0xc400000000, 0xc42007e9a0)
	/root/example/src/github.com/gocql/gocql/host_source.go:642 +0x192
github.com/gocql/gocql.(*Session).handleNewNode(0xc42009e000, 0xc420010d00, 0x10, 0x10, 0x2352, 0x2300)
	/root/example/src/github.com/gocql/gocql/events.go:203 +0x35c
github.com/gocql/gocql.(*Session).handleNodeUp(0xc42009e000, 0xc420010d00, 0x10, 0x10, 0x2352, 0x0)
	/root/example/src/github.com/gocql/gocql/events.go:255 +0x243
github.com/gocql/gocql.(*controlConn).setupConn(0xc42001b580, 0xc4200a40e0, 0x1, 0x1)
	/root/example/src/github.com/gocql/gocql/control.go:259 +0x193
github.com/gocql/gocql.(*controlConn).connect(0xc42001b580, 0xc42000e040, 0x1, 0x1, 0x4, 0x0)
	/root/example/src/github.com/gocql/gocql/control.go:229 +0x18d
github.com/gocql/gocql.(*Session).init(0xc42009e000, 0xc420060360, 0x0)
	/root/example/src/github.com/gocql/gocql/session.go:179 +0x359
github.com/gocql/gocql.NewSession(0xc420010ac0, 0x1, 0x1, 0x690f28, 0x5, 0x0, 0x23c34600, 0x23c34600, 0x2352, 0x0, ...)
	/root/example/src/github.com/gocql/gocql/session.go:143 +0x86f
github.com/gocql/gocql.(*ClusterConfig).CreateSession(0xc42006a120, 0x1, 0x1, 0xc42006a120)
	/root/example/src/github.com/gocql/gocql/cluster.go:153 +0x62
main.main()
	/root/example/src/coding-minds.com/xxx/example/main.go:12 +0x8f
```
